In [14]:
import numpy as np
import pandas as pd

In [15]:
# DATA FRAME DE LA SITUACIÓN DE LAS LENGUASE N EL MUNDO

df_lang = pd.read_csv("../data/languages.csv")

df_lang.info()

df_lang.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 2722 entries, 0 to 2721
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           2722 non-null   int64
 1   Name in English              2722 non-null   str
 2   Name in French               2699 non-null   str
 3   Name in Spanish              2701 non-null   str
 4   Countries                    2721 non-null   str
 5   Country codes alpha 3        2721 non-null   str
 6   ISO639-3 codes               2458 non-null   str
 7   Degree of endangerment       2722 non-null   str
 8   Alternate names              1583 non-null   str
 9   Name in the language         27 non-null     str
 10  Number of speakers           2539 non-null   float64
 11  Sources                      2079 non-null   str
 12  Latitude                     2719 non-null   float64
 13  Longitude                    2719 non-null   float64
 14  Description of the location  1870 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 319.1 KB

,ID,Name in English,Name in French,Name in Spanish,Countries,Country codes alpha 3,ISO639-3 codes,Degree of endangerment,Alternate names,Name in the language,Number of speakers,Sources,Latitude,Longitude,Description of the location
0,1022,South Italian,italien du sud,napolitano-calabrés,Italy,ITA,nap,Vulnerable,Neapolitan; Neapolitan-Calabrese; неаполитанск...,NaN,7500000.0,NaN,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,sicilien,siciliano,Italy,ITA,scn,Vulnerable,NaN,NaN,5000000.0,NaN,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,bas-saxon,bajo sajón,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS","act, drt, frs, gos, nds, sdz, stl, twd, vel, wep",Vulnerable,"Low German, Niedersächsisch, Nedersaksisch, Ni...",Neddersassisch,4800000.0,NaN,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,biélorusse,bielorruso,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",bel,Vulnerable,NaN,NaN,4000000.0,Hienadź Cychun: Weißrussisch. — Lexikon der Sp...,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,lombard,lombardo,"Italy, Switzerland","ITA, CHE",lmo,Definitely endangered,NaN,NaN,3500000.0,NaN,45.7215,9.3273,the region of Lombardy (except the southernmos...
5,405,Romani,romani,romaní,"Albania, Germany, Austria, Belarus, Bosnia and...","ALB, DEU, AUT, BRB, BIH, BGR, HRV, EST, FIN, F...","rmc, rmf, rml, rmn, rmo, rmw, rmy",Definitely endangered,"sinti, vlax, calò",NaN,3500000.0,Yaron Matras: Romani: a linguistic introductio...,46.3165,22.3681,"many European countries, most densely in East-..."
6,2211,Yiddish (Israel),yiddish (Israël),yiddish (Israel),Israel,ISR,ydd,Definitely endangered,Judeo-German,NaN,3000000.0,Neil G. Jacobs: Yiddish: a linguistic introduc...,32.0833,34.8333,"most speakers now live outside Europe, mainly ..."
7,1586,Gondi,gondi,gondí,India,IND,gon,Vulnerable,Gondi; Gaudi; Gondiva; Gondwadi; Goondile; Gou...,NaN,2713790.0,NaN,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
8,1020,Limburgian-Ripuarian,francique ripuaire -limbourgeois,limburgués-ripuarino,"Germany, Belgium, Netherlands","DEU, BEL, NLD","ksh, lim",Vulnerable,Colognian (dialect; in German: Kölsch),NaN,2600000.0,NaN,50.7781,6.0864,Limburg provinces in Belgium and the Netherlan...
9,1943,Quechua of Southern Bolivia,quechua bolivien du sud,quechua boliviano meridional,Bolivia (Plurinational State of),BOL,quh,Vulnerable,NaN,NaN,2300000.0,NaN,-18.0675,-65.7641,"Departments of Cochabamba, Chuquisaca, Potosí ..."

### 1. PREPARACIÓN DATASET LANGUAGES

- [ ] Eliminar columnas con nulo o bajo peso para nuestro análisis.
- [ ] Categorizar la columna Degree of endangerment en una nueva columna.

In [16]:
# Eliminar columnas que poco peso o nulo que no vamos a utilizar en nuestro análisis
df_lang = df_lang.drop(['Name in French', 'Name in Spanish', 'Country codes alpha 3', 'ISO639-3 codes', 'Alternate names', 'Name in the language', 'Sources', 'Latitude', 'Longitude'], axis=1)

In [17]:
# normalizar el nombre de las columnas restantes
df_lang = df_lang.rename(columns={'Name in English': 'Name_English',
    'Degree of endangerment': 'Degree_endagerment',
    'Number of speakers': 'Number_speakers',
    'Description of the location': 'Description_location'
    }
)

In [18]:
# creación de una nueva columna con los valroes de endangerment order categorizada
endangerment_order = {
    'Vulnerable': 1,
    'Definitely endangered': 2,
    'Severely endangered': 3,
    'Critically endangered': 4,
    'Extinct': 5
}
df_lang['endangerment_score'] = df_lang['Degree_endagerment'].map(endangerment_order)

df_lang.head(20)

,ID,Name_English,Countries,Degree_endagerment,Number_speakers,Description_location,endangerment_score
0,1022,South Italian,Italy,Vulnerable,7500000.0,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",1
1,1023,Sicilian,Italy,Vulnerable,5000000.0,"Sicily (Sicilia), southern and central Calabri...",1
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1
3,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1
4,382,Lombard,"Italy, Switzerland",Definitely endangered,3500000.0,the region of Lombardy (except the southernmos...,2
5,405,Romani,"Albania, Germany, Austria, Belarus, Bosnia and...",Definitely endangered,3500000.0,"many European countries, most densely in East-...",2
6,2211,Yiddish (Israel),Israel,Definitely endangered,3000000.0,"most speakers now live outside Europe, mainly ...",2
7,1586,Gondi,India,Vulnerable,2713790.0,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand...",1
8,1020,Limburgian-Ripuarian,"Germany, Belgium, Netherlands",Vulnerable,2600000.0,Limburg provinces in Belgium and the Netherlan...,1
9,1943,Quechua of Southern Bolivia,Bolivia (Plurinational State of),Vulnerable,2300000.0,"Departments of Cochabamba, Chuquisaca, Potosí ...",1
10,1565,Kumaoni,"India, Nepal",Vulnerable,2003783.0,"Uttarakhand, also in Uttar Pradesh, Madhya Pra...",1
11,755,Aymara,"Bolivia (Plurinational State of), Chile, Peru",Vulnerable,2000000.0,"Departamentos de Puno, Moquegua y Tacna, en ...",1
12,349,Emilian-Romagnol,"Italy, San Marino",Definitely endangered,2000000.0,"the region of Emilia-Romagna, parts of the pro...",2
13,399,Piedmontese,Italy,Definitely endangered,2000000.0,"Piedmont Region except the Novara Province, th...",2
14,1021,Venetan,"Croatia, Italy, Slovenia",Vulnerable,2000000.0,"Veneto region, parts of Friuli-Venezia Giulia,...",1
15,1985,Zazaki,Turkey,Vulnerable,2000000.0,"Tunceli, Erzincan, Elazığ and Bingöl provinces...",1
16,1591,Kurux (India),India,Vulnerable,1751489.0,Jharkhand and Bihar,1
17,2065,Tamajeq,Niger,Vulnerable,1750000.0,NaN,1
18,1585,Tulu,India,Vulnerable,1722768.0,"Karnataka, Andhra Pradesh, Kerala",1
19,1556,Kangdi,India,Definitely endangered,1700000.0,Himachal Pradesh,2

### 2. PREPARACIÓN DATASET COUNTRIES

In [19]:
df_count = pd.read_csv("../data/countries of the world.csv")

df_count.info()

df_count.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    str
 1   Region                              227 non-null    str
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    str
 5   Coastline (coast/area ratio)        227 non-null    str
 6   Net migration                       224 non-null    str
 7   Infant mortality (per 1000 births)  224 non-null    str
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    str
 10  Phones (per 1000)                   223 non-null    str
 11  Arable (%)                          225 non-null    str
 12  Crops (%)                           225 non-null    str
 13  Other (%)                           225 non-null    str
 14  Climate                             205 non-null    str
 15  Birthrate                           224 non-null    str
 16  Deathrate                           223 non-null    str
 17  Agriculture                         212 non-null    str
 18  Industry                            211 non-null    str
 19  Service                             212 non-null    str
dtypes: float64(1), int64(2), str(17)
memory usage: 35.6 KB

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN
5,Angola,SUB-SAHARAN AFRICA,12127071,1246700,"9,7","0,13",0,"191,19",1900.0,"42,0","7,8","2,41","0,24","97,35",NaN,"45,11","24,2","0,096","0,658","0,246"
6,Anguilla,LATIN AMER. & CARIB,13477,102,"132,1","59,80","10,76","21,03",8600.0,"95,0","460,0",0,0,100,2,"14,17","5,34","0,04","0,18","0,78"
7,Antigua & Barbuda,LATIN AMER. & CARIB,69108,443,"156,0","34,54","-6,15","19,46",11000.0,"89,0","549,9","18,18","4,55","77,27",2,"16,93","5,37","0,038","0,22","0,743"
8,Argentina,LATIN AMER. & CARIB,39921833,2766890,"14,4","0,18","0,61","15,18",11200.0,"97,1","220,4","12,31","0,48","87,21",3,"16,73","7,55","0,095","0,358","0,547"
9,Armenia,C.W. OF IND. STATES,2976372,29800,"99,9","0,00","-6,47","23,28",3500.0,"98,6","195,7","17,55","2,3","80,15",4,"12,07","8,23","0,239","0,343","0,418"

#### 2.1 Limpieza de formato de datos y columnas
- [ ] Eliminar espacios en blanco en nombres de columnas. Estandarizar nombres a formato snake_case.
- [ ] Comprobar si los separadores decimales están en formato correcto (algunas versiones usan coma en vez de punto).
- [ ] Conversión de tipos
- [ ] Convertir a `category`:
  - Country
  - Region
  - Climate (variable categórica codificada)

In [20]:
# Normalización de los nombres de las columnas
df_count = df_count.rename(columns={'Area (sq. mi.)': 'Area_sq_mi',
    'Pop. Density (per sq. mi.)': 'Pop_density',
    'Coastline (coast/area ratio)': 'Coastline',
    'Net migration': 'Migration',
    'Infant mortality (per 1000 births)': 'Infant_mortality',
    'GDP ($ per capita)': 'GDP',
    'Literacy (%)': 'Literacy',
    'Phones (per 1000)': 'Phones',
    'Arable (%)': 'Arable',
    'Crops (%)': 'Crops',
    'Other (%)': 'Other'
    }
)

In [21]:
def search_cols_with_commas(df):
    cols = []
    for col in df.columns:
        if df[col].dtype == 'object' and df[col].str.contains(',', regex=False, na=False).any():
            cols.append(col)
    return cols

cols_with_commas = search_cols_with_commas(df_count)
print(cols_with_commas)

[]

In [22]:
del cols_with_commas[0] # Eliminamos la columan Country porque realmente es string
print(cols_with_commas)

IndexError: list assignment index out of range

In [24]:
# Convertir los valores numéricos de string a float
for col in cols_with_commas:
    df_count[col] = (
        df_count[col]
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

Para optimizar operaciones como groupby, value_counts. 
Evitar errores al no permitir texto libre. 
Especificar que no tienen carácter numérico
- [ ] Convertir a `category` :
  - Country
  - Region
  - Climate (variable categórica codificada)

In [23]:
df_count["Country"] = df_count["Country"].astype("category")
df_count["Region"] = df_count["Region"].astype("category")
# para categorizar la columna clima nos quedaremos con el primer valor ya que no es un factor con suficiente peso en nuestro EDA
df_count["Climate"] = (
    df_count["Climate"]
    .astype(str)
    .str.split(",", n=1)
    .str[0]
    .str.strip()
    .replace({"nan": None})
    .astype("category")
)
df_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           227 non-null    category
 1   Region            227 non-null    category
 2   Population        227 non-null    int64
 3   Area_sq_mi        227 non-null    int64
 4   Pop_density       227 non-null    str
 5   Coastline         227 non-null    str
 6   Migration         224 non-null    str
 7   Infant_mortality  224 non-null    str
 8   GDP               226 non-null    float64
 9   Literacy          209 non-null    str
 10  Phones            223 non-null    str
 11  Arable            225 non-null    str
 12  Crops             225 non-null    str
 13  Other             225 non-null    str
 14  Climate           205 non-null    category
 15  Birthrate         224 non-null    str
 16  Deathrate         223 non-null    str
 17  Agriculture       212 non-null    str
 18  Industry          211 non-null    str
 19  Service           212 non-null    str
dtypes: category(3), float64(1), int64(2), str(14)
memory usage: 33.1 KB

#### 2.2 Limpieza de formato de datos y columnas
- [ ] Identificar columnas con `NaN`.
- [ ] Decidir estrategia:
  - Imputación (media/mediana) para variables numéricas.
  - Imputación por moda para categóricas.
  - Eliminación de filas si el porcentaje de nulos es bajo.
- [ ] Documentar la decisión (importante para reproducibilidad).

In [25]:
# Identificar columans con NaN
cols_con_nulos = df_count.columns[df_count.isna().any()]
cols_con_nulos

Index(['Migration', 'Infant_mortality', 'GDP', 'Literacy', 'Phones', 'Arable',
       'Crops', 'Other', 'Climate', 'Birthrate', 'Deathrate', 'Agriculture',
       'Industry', 'Service'],
      dtype='str')

In [26]:
def replace_nan_by_mean(df, columns, group_col="Region"):
    for col in columns:
        # Sólo reemplazar si la columna es numérica
        if df[col].dtype.kind in "fi":  # float o int
            df[col] = df[col].fillna(
                df.groupby(group_col)[col].transform("mean")
            )
    return df

In [27]:
df_cof_treated = replace_nan_by_mean(df_count, cols_con_nulos)

df_cof_treated.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           227 non-null    category
 1   Region            227 non-null    category
 2   Population        227 non-null    int64
 3   Area_sq_mi        227 non-null    int64
 4   Pop_density       227 non-null    str
 5   Coastline         227 non-null    str
 6   Migration         224 non-null    str
 7   Infant_mortality  224 non-null    str
 8   GDP               227 non-null    float64
 9   Literacy          209 non-null    str
 10  Phones            223 non-null    str
 11  Arable            225 non-null    str
 12  Crops             225 non-null    str
 13  Other             225 non-null    str
 14  Climate           205 non-null    category
 15  Birthrate         224 non-null    str
 16  Deathrate         223 non-null    str
 17  Agriculture       212 non-null    str
 18  Industry          211 non-null    str
 19  Service           212 non-null    str
dtypes: category(3), float64(1), int64(2), str(14)
memory usage: 33.1 KB

#### 3. Merge de los dos datasets

- Limpiar y dividir la columna Countries en el dataset **df_lang** en listas
- Explode: cada país de la lista → su propia fila
- Limpiar espacios en la nueva columna y normalizar capitalización
- Limpiar y dividir la columna Countries en el dataset **df_cow** en listas
- Mapeo para que coincidan los nombres de los países en los dos datasets
- Merge
- Diagnóstico: cuántas lenguas quedaron sin datos de país

In [ ]:
# 1 Limpiar y dividir la columna Countries en el dataset **df_lang** en listas

df_lang['Countries'] = df_lang['Countries'].str.strip()
df_lang['Countries_list'] = df_lang['Countries'].str.split(',')


# 2 Explode: cada país de la lista → su propia fila

df_lang_exploded = df_lang.explode('Countries_list')


# 3 Limpiar espacios en la nueva columna y normalizar capitalización
df_lang_exploded['Countries_list'] = df_lang_exploded['Countries_list'].str.strip().str.title()


# 4 Limpiar y dividir la columna Countries en el dataset **df_cow** en listas
df_cof_treated['Country'] = df_cof_treated['Country'].str.strip().str.title()

# 5. Mapeo para que coincidan los nombres de los países en los dos datasets
mapeo = {
    "United States Of America": "United States",
    "Russian Federation": "Russia",
    "Bolivia (Plurinational State Of)": "Bolivia",
    "Venezuela (Bolivarian Republic Of)": "Venezuela",
    "Lao People'S Democratic Republic": "Laos",
    "Myanmar": "Burma",
    "Viet Nam": "Vietnam",
    "Iran (Islamic Republic Of)": "Iran",
    "New Caledonia (France)": "New Caledonia",
    "Micronesia (Federated States Of)": "Micronesia, Fed. St.",
    "United Kingdom Of Great Britain And Northern Ireland": "United Kingdom",
    "The Former Yugoslav Republic Of Macedonia": "Macedonia",
    "United Republic Of Tanzania": "Tanzania",
    "Syrian Arab Republic": "Syria",
    "Libyan Arab Jamahiriya": "Libya",
    "Democratic Republic Of The Congo": "Congo, Dem. Rep.",
    "Timor-Leste": "East Timor",
    "Central African Republic": "Central African Rep.",
    "French Polynesia (France)": "French Polynesia",
    "French Guiana (France)": "French Guiana",
    "Côte D'Ivoire": "Ivory Coast",
    "Greenland (Kingdom Of Denmark)": "Greenland",
    "Bosnia And Herzegovina": "Bosnia & Herzegovina",
    "Republic Of Moldova": "Moldova",
    "Congo": "Congo, Repub. Of The",
    "Republic Of Korea": "Korea, South",
    "Guam (U.S.A.)": "Guam",
}

# 6. Aplicar mapeo antes del merge
df_lang_exploded['Countries_list'] = df_lang_exploded['Countries_list'].replace(mapeo)


# 7. Merge
df_merged = df_lang_exploded.merge(
    df_cof_treated,
    left_on='Countries_list',
    right_on='Country',
    how='left'
)

# 8. Diagnóstico: cuántas lenguas quedaron sin datos de país
sin_pais = df_merged['Country'].isna().sum()
print(f"Filas sin match de país: {sin_pais} ({sin_pais/len(df_merged)*100:.1f}%)")
print(f"Filas totales tras explode + merge: {len(df_merged)}")

Filas sin match de país: 11 (0.4%)
Filas totales tras explode + merge: 3075

In [34]:
df_merged.head()

,ID,Name_English,Countries,Degree_endagerment,Number_speakers,Description_location,endangerment_score,Countries_list,Country,Region,...,Phones,Arable,Crops,Other,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,1022,South Italian,Italy,Vulnerable,7500000.0,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",1,Italy,Italy,WESTERN EUROPE,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
1,1023,Sicilian,Italy,Vulnerable,5000000.0,"Sicily (Sicilia), southern and central Calabri...",1,Italy,Italy,WESTERN EUROPE,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Germany,Germany,WESTERN EUROPE,...,"667,9","33,85","0,59","65,56",3,"8,25","10,62","0,009","0,296","0,695"
3,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Denmark,Denmark,WESTERN EUROPE,...,"614,6","54,02","0,19","45,79",3,"11,13","10,36","0,018","0,246","0,735"
4,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Netherlands,Netherlands,WESTERN EUROPE,...,"460,8","26,71","0,97","72,32",3,"10,9","8,68","0,021","0,244","0,736"

In [35]:
# Ver qué tipos hay en la columna
print(df_merged[df_merged['Country'].isna()]['Countries_list'].dtype)

# Ver una muestra de los valores
print(df_merged[df_merged['Country'].isna()]['Countries_list'].value_counts(dropna=False).head(20))

object
Countries_list
Ivory Coast                   4
Montenegro                    1
NaN                           1
Niue                          1
Tokelau                       1
Norfolk Island (Australia)    1
Pitcairn  (U.K.)              1
Palestine                     1
Name: count, dtype: int64

In [38]:
buscar = ["Ivory", "Montenegro", "Niue", "Tokelau", "Norfolk", "Pitcairn", "Palestine"]
for b in buscar:
    matches = [p for p in df_cof_treated['Country'].tolist() if b.lower() in p.lower()]
    print(f"{b}: {matches}")

Ivory: []
Montenegro: []
Niue: []
Tokelau: []
Norfolk: []
Pitcairn: []
Palestine: []

In [39]:
# No aparecen en el df_countries los países anteriores, pero son solo 11

In [43]:
df_merged.info()

df_merged.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    3075 non-null   int64
 1   Name_English          3075 non-null   str
 2   Countries             3074 non-null   str
 3   Degree_endagerment    3075 non-null   str
 4   Number_speakers       2811 non-null   float64
 5   Description_location  2162 non-null   str
 6   endangerment_score    3075 non-null   int64
 7   Countries_list        3074 non-null   object
 8   Region                3064 non-null   category
 9   Population            3064 non-null   float64
 10  Area_sq_mi            3064 non-null   float64
 11  Pop_density           3064 non-null   str
 12  Coastline             3064 non-null   str
 13  Migration             3059 non-null   str
 14  Infant_mortality      3059 non-null   str
 15  GDP                   3064 non-null   float64
 16  Literacy              3024 non-null   str
 17  Phones                3056 non-null   str
 18  Arable                3064 non-null   str
 19  Crops                 3064 non-null   str
 20  Other                 3064 non-null   str
 21  Climate               2659 non-null   category
 22  Birthrate             3057 non-null   str
 23  Deathrate             3053 non-null   str
 24  Agriculture           3056 non-null   str
 25  Industry              3055 non-null   str
 26  Service               3056 non-null   str
dtypes: category(2), float64(4), int64(2), object(1), str(18)
memory usage: 606.8+ KB

,ID,Name_English,Countries,Degree_endagerment,Number_speakers,Description_location,endangerment_score,Countries_list,Region,Population,...,Phones,Arable,Crops,Other,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,1022,South Italian,Italy,Vulnerable,7500000.0,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",1,Italy,WESTERN EUROPE,58133509.0,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
1,1023,Sicilian,Italy,Vulnerable,5000000.0,"Sicily (Sicilia), southern and central Calabri...",1,Italy,WESTERN EUROPE,58133509.0,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Germany,WESTERN EUROPE,82422299.0,...,"667,9","33,85","0,59","65,56",3,"8,25","10,62","0,009","0,296","0,695"
3,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Denmark,WESTERN EUROPE,5450661.0,...,"614,6","54,02","0,19","45,79",3,"11,13","10,36","0,018","0,246","0,735"
4,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Netherlands,WESTERN EUROPE,16491461.0,...,"460,8","26,71","0,97","72,32",3,"10,9","8,68","0,021","0,244","0,736"
5,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Poland,EASTERN EUROPE,38536869.0,...,"306,3","45,91","1,12","52,97",3,"9,85","9,89","0,05","0,311","0,64"
6,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Russia,C.W. OF IND. STATES,142893540.0,...,"280,6","7,33","0,11","92,56",NaN,"9,95","14,65","0,054","0,371","0,575"
7,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Belarus,C.W. OF IND. STATES,10293011.0,...,"319,1","29,55","0,6","69,85",4,"11,16","14,02","0,093","0,316","0,591"
8,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Latvia,BALTICS,2274735.0,...,"321,4","29,67","0,47","69,86",3,"9,24","13,66","0,04","0,261","0,699"
9,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Lithuania,BALTICS,3585906.0,...,"223,4","45,22","0,91","53,87",NaN,"8,75","10,98","0,055","0,325","0,62"

In [42]:
df_merged = df_merged.drop(columns=['Country'])

In [44]:
df_merged.info()

df_merged.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    3075 non-null   int64
 1   Name_English          3075 non-null   str
 2   Countries             3074 non-null   str
 3   Degree_endagerment    3075 non-null   str
 4   Number_speakers       2811 non-null   float64
 5   Description_location  2162 non-null   str
 6   endangerment_score    3075 non-null   int64
 7   Countries_list        3074 non-null   object
 8   Region                3064 non-null   category
 9   Population            3064 non-null   float64
 10  Area_sq_mi            3064 non-null   float64
 11  Pop_density           3064 non-null   str
 12  Coastline             3064 non-null   str
 13  Migration             3059 non-null   str
 14  Infant_mortality      3059 non-null   str
 15  GDP                   3064 non-null   float64
 16  Literacy              3024 non-null   str
 17  Phones                3056 non-null   str
 18  Arable                3064 non-null   str
 19  Crops                 3064 non-null   str
 20  Other                 3064 non-null   str
 21  Climate               2659 non-null   category
 22  Birthrate             3057 non-null   str
 23  Deathrate             3053 non-null   str
 24  Agriculture           3056 non-null   str
 25  Industry              3055 non-null   str
 26  Service               3056 non-null   str
dtypes: category(2), float64(4), int64(2), object(1), str(18)
memory usage: 606.8+ KB

,ID,Name_English,Countries,Degree_endagerment,Number_speakers,Description_location,endangerment_score,Countries_list,Region,Population,...,Phones,Arable,Crops,Other,Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,1022,South Italian,Italy,Vulnerable,7500000.0,"Campania, Lucania (Basilicata), Abruzzi (Abruz...",1,Italy,WESTERN EUROPE,58133509.0,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
1,1023,Sicilian,Italy,Vulnerable,5000000.0,"Sicily (Sicilia), southern and central Calabri...",1,Italy,WESTERN EUROPE,58133509.0,...,"430,9","27,79","9,53","62,68",NaN,"8,72","10,4","0,021","0,291","0,688"
2,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Germany,WESTERN EUROPE,82422299.0,...,"667,9","33,85","0,59","65,56",3,"8,25","10,62","0,009","0,296","0,695"
3,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Denmark,WESTERN EUROPE,5450661.0,...,"614,6","54,02","0,19","45,79",3,"11,13","10,36","0,018","0,246","0,735"
4,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Netherlands,WESTERN EUROPE,16491461.0,...,"460,8","26,71","0,97","72,32",3,"10,9","8,68","0,021","0,244","0,736"
5,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Poland,EASTERN EUROPE,38536869.0,...,"306,3","45,91","1,12","52,97",3,"9,85","9,89","0,05","0,311","0,64"
6,383,Low Saxon,"Germany, Denmark, Netherlands, Poland, Russian...",Vulnerable,4800000.0,"northern Germany, the north-eastern part of th...",1,Russia,C.W. OF IND. STATES,142893540.0,...,"280,6","7,33","0,11","92,56",NaN,"9,95","14,65","0,054","0,371","0,575"
7,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Belarus,C.W. OF IND. STATES,10293011.0,...,"319,1","29,55","0,6","69,85",4,"11,16","14,02","0,093","0,316","0,591"
8,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Latvia,BALTICS,2274735.0,...,"321,4","29,67","0,47","69,86",3,"9,24","13,66","0,04","0,261","0,699"
9,335,Belarusian,"Belarus, Latvia, Lithuania, Poland, Russian Fe...",Vulnerable,4000000.0,Belarus except the Polesian-speaking south-wes...,1,Lithuania,BALTICS,3585906.0,...,"223,4","45,22","0,91","53,87",NaN,"8,75","10,98","0,055","0,325","0,62"